version: '3.3'

services:
  orangehrm:
    image: orangehrm/orangehrm:latest
    container_name: orangehrm_web
    ports:
      - "8080:80"  #80 docker to 8080 host
    environment:
      - ORANGEHRM_DATABASE_HOST=db
      - ORANGEHRM_DATABASE_USER=orangehrm
      - ORANGEHRM_DATABASE_PASSWORD=orangehrm
      - ORANGEHRM_DATABASE_NAME=orangehrm
    depends_on:
      - db

  db:
    image: mariadb:10.4 # Database MariaDB
    container_name: orangehrm_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=orangehrm
      - MYSQL_PASSWORD=orangehrm
      - MYSQL_DATABASE=orangehrm
    volumes:
      - ./db_data:/var/lib/mysql # Mount volume to avoid data loss when container is removed